version: '3.4'

services:
  bodybuilderapp:
    image: ${DOCKER_REGISTRY-}bodybuilderapp
    build:
      context: .
      dockerfile: BodyBuilderApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  redisService:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
  
  jaeger:
   image: jaegertracing/all-in-one:1.49
   container_name: "jaeger_container"
   ports:
    - "4317:4317" #grpc
    - "4318:4318" #http
    - "16686:16686"  #ui
