version: '3.4'

services:
  bodybuilderapp:
    image: ${DOCKER_REGISTRY-}bodybuilderapp
    build:
      context: .
      dockerfile: BodyBuilderApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  seqService:
   image: datalust/seq:latest
   container_name: c_seq
   restart: unless-stopped
   environment:
      ACCEPT_EULA: Y
      SEQ_API_CANONICALURI: https://seq.example.com
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: "$PH"  # Replace with your actual password hash
   volumes:
      - /path/to/seq/data:/data  # Adjust the path as needed
   ports:
      - "5342:80"

  redisService:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
  
  jaeger:
   image: jaegertracing/all-in-one:1.49
   container_name: "jaeger_container"
   ports:
    - "4317:4317" #grpc
    - "4318:4318" #http
    - "16686:16686"  #ui

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    expose:
      - 9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DkIedPPSCb
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    expose:
      - 5601
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: c_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  

networks:
  es-net:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  rabbitmq_data:



